### ISSUE TITLE
Request for dynamic preload like font url in CSS.

### ISSUE THREAD

**Issue by Faisal-Manzer** [w3c/preload#144]
# Problem
The browser supports different formats, ex: Chrome supports WebP and Safari doesn't. Some resources are critical and should be pre-loaded, but can be present in diffrent formats according to the browser.

Below is the example for how someone will load font for diffrent browsers, but if the browser supports 2 or 3 of the format it will load all supported font formats. This will be a wastage of resources at critical rendering time.
```html
<link rel="preload" href="font.woff2" as="font"  type="font/woff2">
<link rel="preload" href="font.woff" as="font"  type="font/woff">
<link rel="preload" href="font.tff" as="font"  type="font/ttf">
```

# Suggested Solution
```html
<link rel="preload" as="font" group>
    <link href="font.woff2" type="font/woff2">
    <link href="font.woff"  type="font/woff">
    <link href="font.tff"  type="font/ttf">
</link>
```
This preload with `group` attribute will download **only one** resource and will stop when it finds a compataible format. Every child of the group will be treated as same object defined in `as` attribute.

# Use Cases
For a media-heavy site, this will be a great optimization of resources. We can preload only one  Image according to supported formats, the same goes for Audio, Video, and Fonts.

I am a newbie and don't know how to edit web specs but I feel this feature important in many use cases.

# Present implementation
This type of thing happens in CSS's `@font-face` _src_. Example is taken from https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face
```css
@font-face {
  font-family: "Open Sans";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```
